#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           2
# bspc config top_padding          32

bspc config normal_border_color "#CBCCC6"
bspc config active_border_color "#CBCCC6"
bspc config focused_border_color "#FFCC66"
bspc config presel_feedback_color "#FFCC66"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config external_rules_command "$(which external_rules)"

bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on  
bspc rule -a Pavucontrol desktop='^4' state=floating follow=on  
bspc rule -a Lxappearance desktop='^4' state=floating follow=on
