#! /bin/sh

sxhkd &
~/.config/polybar/launch.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           5

# Border colors
bspc config normal_border_color     "#c8c8c8" 
bspc config focused_border_color    "#c8ae9d"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
